// Path: app/src/main/java/uk/ac/hope/mcse/android/coursework/model/JournalEntry.java
package uk.ac.hope.mcse.android.coursework.model;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.PrimaryKey;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
// Removed AtomicLong as ID will be auto-generated by Room

@Entity(tableName = "journal_entries") // Defines the table name
public class JournalEntry {

    @PrimaryKey(autoGenerate = true) // Room will auto-generate IDs
    private long id;

    @ColumnInfo(name = "title")
    private String title;

    @ColumnInfo(name = "content")
    private String content;

    @ColumnInfo(name = "entry_date_millis")
    private long entryDateMillis;

    private Double latitude;
    private Double longitude;

    // Room needs a public constructor (or one it can access).
    public JournalEntry(String title, String content, long entryDateMillis) {
        this.title = title;
        this.content = content;
        this.entryDateMillis = entryDateMillis;
        this.latitude = null; // Initialises to null
        this.longitude = null; // Initialises to null
    }

    // Getters and Setters (Room needs these or public fields)
    public long getId() {
        return id;
    }

    public void setId(long id) { // Setter for ID is needed by Room
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public long getEntryDateMillis() {
        return entryDateMillis;
    }

    // Adds getters and setters for latitude and longitude
    public Double getLatitude() {
        return latitude;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public void setEntryDateMillis(long entryDateMillis) {
        this.entryDateMillis = entryDateMillis;
    }

    public String getFormattedDate() {
        SimpleDateFormat sdf = new SimpleDateFormat("EEE, dd MMM yyyy", Locale.getDefault());
        return sdf.format(new Date(entryDateMillis));
    }

    @Override
    public String toString() {
        return getTitle() + " (" + getFormattedDate() + ")";
    }
}